// 拾语 · 三语例句库（每种30句，一个月不重样）
// 结构：{ text, reading, translation, grammar }
const SENTENCES = {

en: [
  { text: "I've been meaning to ask you...", reading: "[aɪv bɪn ˈmiːnɪŋ tu æsk ju]", translation: "我一直想问你…", grammar: "have been + -ing 一直想做某事" },
  { text: "It slipped my mind.", reading: "[ɪt slɪpt maɪ maɪnd]", translation: "我一时忘了。", grammar: "slip one's mind = 从脑中滑走，很地道的说法" },
  { text: "Good to know!", reading: "[ɡʊd tə noʊ]", translation: "学到了！/ 知道了！", grammar: "比 I know 更自然的口语回应" },
  { text: "I'll get back to you on that.", reading: "[aɪl ɡet bæk tə ju ɒn ðæt]", translation: "我那件事回头再找你。", grammar: "get back to = 回头再说/再答复" },
  { text: "It's not my thing.", reading: "[ɪts nɑt maɪ θɪŋ]", translation: "这不是我的菜。", grammar: "not one's thing = 不擅长/不喜欢" },
  { text: "I'm not a morning person.", reading: "[aɪm nɑt ə ˈmɔrnɪŋ ˈpɜrsən]", translation: "我不是早起的人。", grammar: "a morning person = 早起型人，同理 night person" },
  { text: "Let's call it a day.", reading: "[lets kɔl ɪt ə deɪ]", translation: "今天到此为止吧。", grammar: "call it a day = 收工/到此为止" },
  { text: "I couldn't help but laugh.", reading: "[aɪ ˈkʊdnt help bʌt læf]", translation: "我忍不住笑了。", grammar: "can't help but = 忍不住做某事" },
  { text: "It's up to you.", reading: "[ɪts ʌp tə ju]", translation: "你说了算。", grammar: "up to + 人 = 由某人决定" },
  { text: "I'm looking forward to it.", reading: "[aɪm ˈlʊkɪŋ ˈfɔrwərd tə ɪt]", translation: "我很期待。", grammar: "look forward to + 名词/-ing，to 是介词" },
  { text: "That makes sense.", reading: "[ðæt meɪks sens]", translation: "有道理。", grammar: "make sense = 说得通，make no sense = 没道理" },
  { text: "I'd rather stay home.", reading: "[aɪd ˈræðər steɪ hoʊm]", translation: "我宁愿待在家。", grammar: "would rather = 宁愿，后面直接加动词原形" },
  { text: "It's not worth it.", reading: "[ɪts nɑt wɜrθ ɪt]", translation: "不值得。", grammar: "worth + 名词/-ing = 值得做某事" },
  { text: "I ran into an old friend.", reading: "[aɪ ræn ˈɪntə ən oʊld frend]", translation: "我偶遇了一位老朋友。", grammar: "run into = 偶遇，不是跑进去" },
  { text: "Take your time.", reading: "[teɪk jɔr taɪm]", translation: "慢慢来，不急。", grammar: "take one's time = 不用着急" },
  { text: "I'm getting used to it.", reading: "[aɪm ˈɡetɪŋ juzd tə ɪt]", translation: "我正在慢慢习惯。", grammar: "get used to = 逐渐习惯（过程）" },
  { text: "It's none of your business.", reading: "[ɪts nʌn əv jɔr ˈbɪznəs]", translation: "不关你的事。", grammar: "none of one's business = 和某人无关" },
  { text: "I'd like to pick up where we left off.", reading: "[aɪd laɪk tə pɪk ʌp wer wi left ɔf]", translation: "我想从上次停下的地方接着来。", grammar: "pick up where we left off = 续上之前的事情" },
  { text: "You can count on me.", reading: "[ju kæn kaʊnt ɑn mi]", translation: "你可以靠我。", grammar: "count on = 依靠/指望" },
  { text: "It's on the tip of my tongue.", reading: "[ɪts ɑn ðə tɪp əv maɪ tʌŋ]", translation: "话到嘴边想不起来。", grammar: "on the tip of one's tongue = 马上想起但还想不起来" },
  { text: "I've got a lot on my plate.", reading: "[aɪv ɡɑt ə lɑt ɑn maɪ pleɪt]", translation: "我手头一堆事。", grammar: "have a lot on one's plate = 很忙/很多事要处理" },
  { text: "Better late than never.", reading: "[ˈbetər leɪt ðæn ˈnevər]", translation: "迟到总比不到好。", grammar: "比较级固定句式：Better A than B" },
  { text: "I didn't see that coming.", reading: "[aɪ ˈdɪdnt si ðæt ˈkʌmɪŋ]", translation: "完全没料到。", grammar: "see something coming = 预料到某事" },
  { text: "It's easier said than done.", reading: "[ɪts ˈiziər sed ðæn dʌn]", translation: "说起来容易做起来难。", grammar: "比较级：easier said than done" },
  { text: "I'm all ears.", reading: "[aɪm ɔl ɪrz]", translation: "我洗耳恭听。", grammar: "be all ears = 全神贯注地听" },
  { text: "That's the last straw.", reading: "[ðæts ðə læst strɔ]", translation: "忍无可忍了。", grammar: "the last straw = 压垮骆驼的最后一根稻草" },
  { text: "I'll sleep on it.", reading: "[aɪl slip ɑn ɪt]", translation: "我睡一觉明天决定。", grammar: "sleep on it = 不立刻决定，明天再说" },
  { text: "No hard feelings.", reading: "[noʊ hɑrd ˈfilɪŋz]", translation: "没关系的/不记仇。", grammar: "hard feelings = 怨恨/不愉快" },
  { text: "I'm in two minds about it.", reading: "[aɪm ɪn tu maɪndz əˈbaʊt ɪt]", translation: "我有点犹豫。", grammar: "be in two minds = 纠结/拿不定主意" },
  { text: "You made my day!", reading: "[ju meɪd maɪ deɪ]", translation: "你让我今天很开心！", grammar: "make one's day = 让某人一整天都开心" }
],

jp: [
  { text: "そう言えば、昨日の会議はどうだった？", reading: "そういえば、きのうのかいぎはどうだった？", translation: "说起来，昨天的会怎么样？", grammar: "そう言えば = 说起来/对了（引出新话题）" },
  { text: "ちょっと手伝ってもらえますか？", reading: "ちょっとてつだってもらえますか？", translation: "能帮我一下吗？", grammar: "～てもらう = 请别人为自己做某事" },
  { text: "もう少しで終わります。", reading: "もうすこしでおわります。", translation: "马上就结束了。", grammar: "もう少しで = 还差一点就……" },
  { text: "そんなことないよ。", reading: "そんなことないよ。", translation: "才没那回事呢。", grammar: "そんなことない = 否定对方的话，口语常用" },
  { text: "どういう意味ですか？", reading: "どういういみですか？", translation: "什么意思？", grammar: "どういう + 名詞 = 什么样的……" },
  { text: "やってみないと分からないよ。", reading: "やってみないとわからないよ。", translation: "不试试怎么知道呢。", grammar: "～てみる = 试着做某事，～ないと分からない = 不做不知道" },
  { text: "お先に失礼します。", reading: "おさきにしつれいします。", translation: "我先走了（下班/离开时用）。", grammar: "お先に = 我先……，职场常用寒暄" },
  { text: "これってどうやって使うの？", reading: "これってどうやってつかうの？", translation: "这个怎么用啊？", grammar: "どうやって = 怎么做/怎么用，询问方法" },
  { text: "やっぱりそうだったんだ。", reading: "やっぱりそうだったんだ。", translation: "果然是这样啊。", grammar: "やっぱり = 果然/还是，表示和自己预想一致" },
  { text: "気にしないでください。", reading: "きにしないでください。", translation: "请别介意。", grammar: "気にする = 在意，～ないで = 请不要……" },
  { text: "今のところは大丈夫です。", reading: "いまのところはだいじょうぶです。", translation: "目前还好。", grammar: "今のところ = 目前/现阶段" },
  { text: "せっかくだけど、遠慮します。", reading: "せっかくだけど、えんりょします。", translation: "难得的好意，但我不去了。", grammar: "せっかく = 难得/特意，遠慮する = 婉拒" },
  { text: "なんとなくそう思った。", reading: "なんとなくそうおもった。", translation: "不知怎么就那么觉得。", grammar: "なんとなく = 不由得/莫名地" },
  { text: "どっちでもいいよ。", reading: "どっちでもいいよ。", translation: "哪个都行。", grammar: "どっちでも = 哪一个都……，いい = 可以" },
  { text: "お疲れ様です。", reading: "おつかれさまです。", translation: "辛苦了（日常万能问候）。", grammar: "お疲れ様 = 辛苦了，职场/日常都用" },
  { text: "それってありえないよ。", reading: "それってありえないよ。", translation: "那不可能吧/太离谱了。", grammar: "ありえない = 不可能/难以置信" },
  { text: "ちょっと考えさせてください。", reading: "ちょっとかんがえさせてください。", translation: "让我考虑一下。", grammar: "～させてください = 请让我做某事（使役+请求）" },
  { text: "なかなか上手くいかないなあ。", reading: "なかなかうまくいかないなあ。", translation: "怎么就是做不好呢。", grammar: "なかなか～ない = 怎么也不……" },
  { text: "もしもし、今大丈夫？", reading: "もしもし、いまだいじょうぶ？", translation: "喂，现在方便吗？", grammar: "もしもし = 打电话专用，面对面不用" },
  { text: "すごく助かりました！", reading: "すごくたすかりました！", translation: "帮大忙了！", grammar: "助かる = 得到帮助/得救，比「ありがとう」更有分量" },
  { text: "それはさておき、本題に入ろう。", reading: "それはさておき、ほんだいにはいろう。", translation: "那个先放一边，进入正题吧。", grammar: "さておき = 暂且不提，～に入ろう = 进入……吧" },
  { text: "あいにくですが、予定が入っています。", reading: "あいにくですが、よていがはいっています。", translation: "不巧，已经有安排了。", grammar: "あいにく = 不凑巧/遗憾，委婉拒绝" },
  { text: "まさかそんなことになるとは思わなかった。", reading: "まさかそんなことになるとはおもわなかった。", translation: "万万没想到会变成这样。", grammar: "まさか～とは思わなかった = 万万没想到" },
  { text: "いつでも好きな時に来てね。", reading: "いつでもすきなときにきてね。", translation: "随时都可以来哦。", grammar: "いつでも = 任何时候，好きな時に = 想什么时候就什么时候" },
  { text: "ちょうどいいところに来たね。", reading: "ちょうどいいところにきたね。", translation: "你来得正好。", grammar: "ちょうどいい = 刚好/正合适" },
  { text: "せっかちにならないで、ゆっくりやろう。", reading: "せっかちにならないで、ゆっくりやろう。", translation: "别急，慢慢来吧。", grammar: "せっかち = 急性子/急躁，～ないで = 不要……" },
  { text: "そういうことだったのか！", reading: "そういうことだったのか！", translation: "原来是这么回事啊！", grammar: "そういうこと = 这么回事，～のか = 感叹/恍然大悟" },
  { text: "何かあったら教えてね。", reading: "なにかあったらおしえてね。", translation: "有什么事告诉我哦。", grammar: "～たら = 如果……了，表条件" },
  { text: "だんだん慣れてきた。", reading: "だんだんなれてきた。", translation: "慢慢习惯了。", grammar: "だんだん = 渐渐，～てきた = ……起来了" },
  { text: "無理しないでくださいね。", reading: "むりしないでくださいね。", translation: "别太勉强自己哦。", grammar: "無理する = 勉强/硬撑，～ないで = 别……" }
],

fr: [
  { text: "Qu'est-ce que tu fais ?", reading: "[kes kə ty fɛ]", translation: "你在干嘛呢？", grammar: "Qu'est-ce que = 什么（疑问句固定结构）" },
  { text: "J'allais justement te le dire.", reading: "[ʒalɛ ʒystəmɑ̃ tə lə dir]", translation: "我正要跟你说这个呢。", grammar: "aller 未完成过去式 + justement = 正好要做" },
  { text: "Ça dépend.", reading: "[sa depɑ̃]", translation: "看情况。", grammar: "Ça dépend de + 名词 = 取决于……" },
  { text: "T'inquiète pas.", reading: "[tɛ̃kjɛt pa]", translation: "别担心。（口语）", grammar: "Ne t'inquiète pas 的口语缩略，ne 常被省略" },
  { text: "C'est pas grave.", reading: "[se pa ɡrav]", translation: "没关系的。", grammar: "pas grave = 不严重，口语省略 ne" },
  { text: "Je n'en peux plus.", reading: "[ʒə nɑ̃ pø ply]", translation: "我受不了了/我撑不住了。", grammar: "ne...plus = 不再，en pouvoir = 承受" },
  { text: "Tu as raison.", reading: "[ty a rɛzɔ̃]", translation: "你说得对。", grammar: "avoir raison = 是对的，avoir tort = 是错的" },
  { text: "Ça marche !", reading: "[sa marʃ]", translation: "没问题！/ 行！", grammar: "marcher = 运行/走，口语「行得通」" },
  { text: "Je viens d'arriver.", reading: "[ʒə vjɛ̃ darive]", translation: "我刚到。", grammar: "venir de + 动词原形 = 刚刚做完某事" },
  { text: "Il faut que j'y aille.", reading: "[il fo kə ʒi aj]", translation: "我得走了。", grammar: "il faut que + 虚拟式 = 必须做某事" },
  { text: "Je suis en train de manger.", reading: "[ʒə sɥi ɑ̃ trɛ̃ də mɑ̃ʒe]", translation: "我正在吃饭。", grammar: "être en train de = 正在做某事（现在进行时）" },
  { text: "Tu me manques.", reading: "[ty mə mɑ̃k]", translation: "我想你。", grammar: "manquer à qn = 某人想念……，主语是你不是「我」" },
  { text: "J'en ai marre.", reading: "[ʒɑ̃ ne mar]", translation: "我烦了/够了。", grammar: "en avoir marre de = 受够了某事" },
  { text: "C'est n'importe quoi !", reading: "[se nɛ̃pɔrt kwa]", translation: "胡说八道！/ 乱七八糟！", grammar: "n'importe quoi = 任意……/胡扯" },
  { text: "Peu importe.", reading: "[pø ɛ̃pɔrt]", translation: "无所谓。/ 不管了。", grammar: "peu importe + 名词 = ……不重要" },
  { text: "Tant mieux !", reading: "[tɑ̃ mjø]", translation: "那太好了！", grammar: "tant mieux = 那就好/太好了，反义词 tant pis = 那算了" },
  { text: "Tant pis.", reading: "[tɑ̃ pi]", translation: "那就算了。", grammar: "表示无奈接受，不要和 tant mieux 弄混" },
  { text: "Tout à fait.", reading: "[tut a fɛ]", translation: "完全正确。", grammar: "tout à fait = 完全地，表示强烈同意" },
  { text: "Pas du tout.", reading: "[pa dy tu]", translation: "一点也不。", grammar: "pas du tout = 完全不，比 non 语气更强" },
  { text: "Tout le monde est là ?", reading: "[tu lə mɔ̃d e la]", translation: "大家都在吗？", grammar: "tout le monde = 大家，虽是复数意义但动词用单数" },
  { text: "Je m'en fiche.", reading: "[ʒə mɑ̃ fiʃ]", translation: "我不在乎。（中性）", grammar: "s'en ficher = 不在乎，比 s'en foutre 礼貌" },
  { text: "Ça vaut le coup.", reading: "[sa vo lə ku]", translation: "值的。/ 划算。", grammar: "valoir le coup = 值得，couper = 成本/代价" },
  { text: "N'importe quand.", reading: "[nɛ̃pɔrt kɑ̃]", translation: "随便什么时候。", grammar: "n'importe + 疑问词 = 无论……" },
  { text: "Je te tiens au courant.", reading: "[ʒə tə tjɛ̃ o kurɑ̃]", translation: "有消息我告诉你。", grammar: "tenir qn au courant = 让某人知情" },
  { text: "C'est à mon tour.", reading: "[se ta mɔ̃ tur]", translation: "轮到我了。", grammar: "à mon/ton/son tour = 轮到某人" },
  { text: "On y va ?", reading: "[ɔ̃ ni va]", translation: "走吧？/ 开始吧？", grammar: "on = 我们（口语比 nous 常用），y = 到那里" },
  { text: "Je compte sur toi.", reading: "[ʒə kɔ̃t syr twa]", translation: "我就靠你了。", grammar: "compter sur = 依靠，介词 sur 不是 on 的直译" },
  { text: "Ça fait longtemps !", reading: "[sa fɛ lɔ̃tɑ̃]", translation: "好久不见！", grammar: "ça fait + 时间 = 已经……时间了" },
  { text: "Je n'y crois pas.", reading: "[ʒə ni krwa pa]", translation: "我不信。", grammar: "y croire = 相信那件事，y 代替 à + 事物" },
  { text: "Tout va bien.", reading: "[tu va bjɛ̃]", translation: "一切都好。", grammar: "tout va bien = 万事顺利，tout 作主语动词用第三人称单数" }
]

};
